pipeline{
    agent any

    environment{
        FRONTEND_IMAGE_DEV= 'avejlanjekar45/employee-management-frontend-dev'
        FRONTEND_IMAGE_QA= 'avejlanjekar45/employee-management-frontend-qa'
        FRONTEND_IMAGE_UAT= 'avejlanjekar45/employee-management-frontend-uat'
        FRONTEND_IMAGE_PROD='avejlanjekar45/employee-management-frontend-prod'

        REGISTRY_URL= 'https://registry.hub.docker.com'

        DEV_DH_CREDENTIALS= 'dockerhub-credentials'
        QA_DH_CREDENTIALS= 'dockerhub-credentials'
        UAT_DH_CREDENTIALS= 'dockerhub-credentials'
        PROD_DH_CREDENTIALS= 'dockerhub-credentials'
    }

    parameters{
        choice(
            name: 'Environment',
            choices: ["DEV","QA","UAT","PROD"],
            description: "Select deployment environment"
        )
    }

    stages{

        stage("build & push"){
            when {
                expression{
                    params.Environment == "DEV"
                }
            }
            steps{
                script{

                    def frontend= docker.build("${env.FRONTEND_IMAGE_DEV}:${GIT_COMMIT}","./frontend/Jenkinsfile")

                    docker.withRegistry("${env.REGISTRY_URL}","${env.DEV_DH_CREDENTIALS}"){
                        frontend.push()
                    }

                    withKubeConfig(credentialsId: 'eks-kubeconfig'){
                        sh 'echo deploying to employee-dev namespace...'
                        sh 'kubectl apply -f kube/frontend-deployment.yml'
                        sh 'kubectl apply -f kube/frontend-service.yml'
                        sh 'kubectl apply -f kube/ingress.yml'
                    }
                }
            }
        }

        stage("promote image DEV to QA"){
            when{
                expression{
                    params.Environment == "QA"
                }
            }
            steps{
                script{
                    docker.withRegistry("${env.REGISTRY_URL}","${env.DEV_DH_CREDENTIALS}"){
                        docker.image("${env.FRONTEND_IMAGE_DEV}:${GIT_COMMIT}").pull()
                    }

                    sh "docker tag ${env.FRONTEND_IMAGE_DEV}:${GIT_COMMIT} ${env.FRONTEND_IMAGE_QA}:${GIT_COMMIT}"

                    docker.withRegistry("${env.REGISTRY_URL}","${env.QA_DH_CREDENTIALS}"){
                        docker.image("${env.FRONTEND_IMAGE_QA}:${GIT_COMMIT}").push()
                    }

                    withKubeConfig(credentialsId: 'eks-kubeconfig'){
                        sh 'kubectl apply -f kube/frontend-deployment.yml'
                        sh 'kubectl apply -f kube/frontend-service.yml'
                        sh 'kubectl apply -f kube/ingress.yml'
                    }
                }
            }
        }

        stage("promote image QA to UAT"){
            when {
                expression{
                    params.Environment == "UAT"
                }
            }
            steps{
                script{
                    docker.withRegistry("${env.REGISTRY_URL}","${env.QA_DH_CREDENTIALS}"){
                        docker.image("${env.FRONTEND_IMAGE_QA}:${GIT_COMMIT}").pull()
                    }

                    sh "docker tag ${env.FRONTEND_IMAGE_QA}:${GIT_COMMIT} ${env.FRONTEND_IMAGE_UAT}:${GIT_COMMIT}"

                    docker.withRegistry("${env.REGISTRY_URL}","${env.UAT_DH_CREDENTIALS}"){
                        docker.image("${env.FRONTEND_IMAGE_UAT}:${GIT_COMMIT}").push()
                    }

                    withKubeConfig(credentialsId: 'eks-kubeconfig'){
                        sh 'echo deploying to employee-UAT namespace...'
                        sh 'kubectl apply -f kube/frontend-deployment.yml'
                        sh 'kubectl apply -f kube/frontend-service.yml'
                        sh 'kubectl apply -f kube/ingress.yml'
                    }
                }
            }
        }

        stage("approval for prod"){
            when{
                expression{
                    params.Environment == 'PROD'
                }
            }
            steps{
                input message: 'Promote the image from UAT to PROD?',
                      ok: "Promote to PROD"
            }
        }
        

        stage("Promote image from UAT to PROD"){
            when{
                expression{
                    params.Environment == "PROD"
                }
            }
            steps{
                script{
                    docker.withRegistry("${env.REGISTRY_URL}","${env.UAT_DH_CREDENTIALS}"){
                        docker.image("${env.FRONTEND_IMAGE_UAT}:${GIT_COMMIT}").pull()
                    }

                    sh "docker tag ${env.FRONTEND_IMAGE_UAT}:${GIT_COMMIT} ${env.FRONTEND_IMAGE_PROD}:${GIT_COMMIT}"

                    docker.withRegistry("${env.REGISTRY_URL}","${env.PROD_DH_CREDENTIALS}"){
                        docker.image("${env.FRONTEND_IMAGE_PROD}:${GIT_COMMIT}").push()
                    }

                    withKubeConfig(credentialsId: 'eks-kubeconfig'){
                        sh 'echo deploying to employee-prod namespace...'
                        sh 'kubectl apply -f kube/frontend-deployment.yml'
                        sh 'kubectl apply -f kube/frontend-service.yml'
                        sh 'kubectl apply -f kube/ingress.yml'
                    }
                }
            }
        }
    }
    post{
        always{
            cleanWs()
        }
    }
}