pipeline{
    agent any

    environment{

        BACKEND_IMAGE_DEV= 'avejlanjekar45/employee-management-backend-dev'
        BACKEND_IMAGE_QA= 'avejlanjekar45/employee-management-backend-qa'
        BACKEND_IMAGE_UAT='avejlanjekar45/employee-management-backend-uat'
        BACKEND_IMAGE_PROD='avejlanjekar45/employee-management-backend-prod'

        REGISTRY_URL= 'https://registry.hub.docker.com'

        DEV_DH_CREDENTIALS= 'dockerhub-credentials'
        QA_DH_CREDENTIALS= 'dockerhub-credentials'
        UAT_DH_CREDENTIALS= 'dockerhub-credentials'
        PROD_DH_CREDENTIALS= 'dockerhub-credentials'
    }

    parameters{
        choice(
            name: 'Environment',
            choices: ["dev","qa","uat","prod"],
            description: "Select deployment environment"
        )
    }

    stages{

        stage("build & push"){
            when {
                expression{
                    params.Environment == "dev"
                }
            }
            steps{
                script{
                    def backend= docker.build("${env.BACKEND_IMAGE_DEV}:${GIT_COMMIT}","./backend")

                    docker.withRegistry("${env.REGISTRY_URL}","${env.DEV_DH_CREDENTIALS}"){
                        backend.push()
                    }

                    withKubeConfig(credentialsId: 'eks-kubeconfig', namespace: 'employee-dev'){
                        sh 'echo deploying to employee-dev namespace...'
                        sh "sed -i -e 's/{{ENV}}/${params.Environment}/g' -e 's/{{COMMITID}}/${env.GIT_COMMIT}/g' kube/backend-deployment.yml "
                        sh 'kubectl apply -f kube/configmap.yml'
                        sh 'kubectl apply -f kube/db-secret.yml'
                        sh 'kubectl apply -f kube/mysql-deployment.yml'
                        sh 'kubectl apply -f kube/mysql-service.yml'
                        sh 'kubectl apply -f kube/backend-deployment.yml'
                        sh 'kubectl apply -f kube/backend-service.yml'
                    }
                }
            }
        }

        stage("promote image DEV to QA"){
            when{
                expression{
                    params.Environment == "qa"
                }
            }
            steps{
                script{
                    docker.withRegistry("${env.REGISTRY_URL}","${env.DEV_DH_CREDENTIALS}"){
                        docker.image("${env.BACKEND_IMAGE_DEV}:${GIT_COMMIT}").pull()
                    }

                    sh "docker tag ${env.BACKEND_IMAGE_DEV}:${GIT_COMMIT} ${env.BACKEND_IMAGE_QA}:${GIT_COMMIT}"

                    docker.withRegistry("${env.REGISTRY_URL}","${env.QA_DH_CREDENTIALS}"){
                        docker.image("${env.BACKEND_IMAGE_QA}:${GIT_COMMIT}").push()
                    }

                    withKubeConfig(credentialsId: 'eks-kubeconfig', namespace: 'employee-qa'){
                        sh 'echo deploying to employee-qa namespace...'
                        sh "sed -i -e 's/{{ENV}}/${params.Environment}/g' -e 's/{{COMMITID}}/${env.GIT_COMMIT}/g' kube/backend-deployment.yml "
                        sh 'kubectl apply -f kube/configmap.yml'
                        sh 'kubectl apply -f kube/db-secret.yml'
                        sh 'kubectl apply -f kube/mysql-deployment.yml'
                        sh 'kubectl apply -f kube/mysql-service.yml'
                        sh 'kubectl apply -f kube/backend-deployment.yml'
                        sh 'kubectl apply -f kube/backend-service.yml'
                    }
                }
            }
        }

        stage("promote image QA to UAT"){
            when {
                expression{
                    params.Environment == "uat"
                }
            }
            steps{
                script{
                    docker.withRegistry("${env.REGISTRY_URL}","${env.QA_DH_CREDENTIALS}"){
                        docker.image("${env.BACKEND_IMAGE_QA}:${GIT_COMMIT}").pull()
                    }

                    sh "docker tag ${env.BACKEND_IMAGE_QA}:${GIT_COMMIT} ${env.BACKEND_IMAGE_UAT}:${GIT_COMMIT}"

                    docker.withRegistry("${env.REGISTRY_URL}","${env.UAT_DH_CREDENTIALS}"){
                        docker.image("${env.BACKEND_IMAGE_UAT}:${GIT_COMMIT}").push()
                    }

                    withKubeConfig(credentialsId: 'eks-kubeconfig', namespace: 'employee-uat'){
                        sh 'echo deploying to employee-uat namespace...'
                        sh "sed -i -e 's/{{ENV}}/${params.Environment}/g' -e 's/{{COMMITID}}/${env.GIT_COMMIT}/g' kube/backend-deployment.yml "
                        sh 'kubectl apply -f kube/configmap.yml'
                        sh 'kubectl apply -f kube/db-secret.yml'
                        sh 'kubectl apply -f kube/mysql-deployment.yml'
                        sh 'kubectl apply -f kube/mysql-service.yml'
                        sh 'kubectl apply -f kube/backend-deployment.yml'
                        sh 'kubectl apply -f kube/backend-service.yml'
                    }
                }
            }
        }

        stage("approval for prod"){
            when{
                expression{
                    params.Environment == 'prod'
                }
            }
            steps{
                input message: 'Promote the image from UAT to PROD?',
                      ok: "Promote to PROD"
            }
        }
        

        stage("Promote image from UAT to PROD"){
            when{
                expression{
                    params.Environment == "prod"
                }
            }
            steps{
                script{
                    docker.withRegistry("${env.REGISTRY_URL}","${env.UAT_DH_CREDENTIALS}"){
                        docker.image("${env.BACKEND_IMAGE_UAT}:${GIT_COMMIT}").pull()
                    }

                    sh "docker tag ${env.BACKEND_IMAGE_UAT}:${GIT_COMMIT} ${env.BACKEND_IMAGE_PROD}:${GIT_COMMIT}"

                    docker.withRegistry("${env.REGISTRY_URL}","${env.PROD_DH_CREDENTIALS}"){
                        docker.image("${env.BACKEND_IMAGE_PROD}:${GIT_COMMIT}").push()
                    }

                    withKubeConfig(credentialsId: 'eks-kubeconfig', namespace: 'employee-prod'){
                        sh 'echo deploying to employee-prod namespace...'
                        sh "sed -i -e 's/{{ENV}}/${params.Environment}/g' -e 's/{{COMMITID}}/${env.GIT_COMMIT}/g' kube/backend-deployment.yml "
                        sh 'kubectl apply -f kube/configmap.yml'
                        sh 'kubectl apply -f kube/db-secret.yml'
                        sh 'kubectl apply -f kube/mysql-deployment.yml'
                        sh 'kubectl apply -f kube/mysql-service.yml'
                        sh 'kubectl apply -f kube/backend-deployment.yml'
                        sh 'kubectl apply -f kube/backend-service.yml'
                    }
                }
            }
        }
    }
    post{
        always{
            cleanWs()
        }
    }
}